# Generated by Django 5.2.12 on 2026-04-07 12:57

import django.core.validators
import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Allowed types: jpg, jpeg, png, gif, webp. Max size: 5 MB.', upload_to='products/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), store.models.validate_image_file_size, store.models.validate_image_content_type])),
                ('thumbnail', models.ImageField(blank=True, editable=False, help_text='Auto-generated 300×300 thumbnail.', upload_to='products/thumbnails/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility.', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the main display image for the product.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
