# Generated by Django 5.2.12 on 2026-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productimage',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public_id for the full-size image.', max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for the full-size image.', max_length=1000),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public_id for the auto-generated thumbnail.', max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for the 300x300 thumbnail.', max_length=1000),
        ),
    ]
